In [2]:
import numpy as np

ARRAYS

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])         
arr2 = np.array((1, 2, 3, 4, 5), dtype='f')             # dtype - explicitly defines the datatype of the array

print(arr1)
print(arr2)
print(type(arr1))

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a * b)

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
# print(a.ndim)       # Prints the dimension of the array
print(a[2])
print(a[2, 0])

b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# print(b.ndim)
print(b[0])
print(b[0, 1, 0])

In [ ]:
b = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
b.shape           # b.shape() --> Returns a tuple and it contains (2, 2, 4)
# 2 -> How many 3D arrays? 
# 2 -> In each 3D array, how many 1D arrays are there?
# 4 -> How many items in each of those 3D arrays

b.shape[0]      # Tells us how many 3D arrays only (NOT THE REMAINING 2 THINGS)
b.shape[1]     
b.shape[2]     

In [ ]:
b.size      # How many total number of elements in the array


In [ ]:
b.nbytes    # How many total number of bytes is it taking in total

In [ ]:
a = np.arange(50)           # Quick way to initialize an array from 0 to n-1 
print(a)                    # Please note the spelling - it's 'arange' and NOT 'arrange'


b = np.arange(10, 50)       # Start from 10 upto n-1 (49)
print(b)

c = np.arange(5, 50, 5)     # Start from 5 upto 49 with skip value of 5 (5, 10, 15, 20, 25...)     
print(c)

In [ ]:
a = np.random.permutation(np.arange(1, 10))     # It shuffles and re-arranges all the values from 1 to 9 and everytime you print, you get a new order!
print(a)

In [ ]:
a = np.random.randint(1, 100)
print(a)
type(a)

In [ ]:
a = np.arange(10)
b = a.reshape(2, 5)         # Converted the 1D array into 2 rows and 5 cols matrix and stored in 'b' using "a.reshape(rows, cols)" syntax
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [206]:
c = np.random.rand(2, 3, 3, 2)
# 2 -> 2 3D arrays
# 3 -> Each 3D array has 3 2D arrays
# 3 -> Each 2D array has 3 1D arrays
# 2 -> Each 1D array has 2 elements

print(c.ndim)
print(c)

4
[[[[0.92985359 0.40560723]
   [0.72350461 0.76483398]
   [0.63956706 0.85615231]]

  [[0.69585375 0.99753923]
   [0.88076294 0.80135311]
   [0.38739364 0.83037709]]

  [[0.08194217 0.81433937]
   [0.26565129 0.3776894 ]
   [0.19621307 0.8546416 ]]]


 [[[0.08582215 0.36356409]
   [0.91899533 0.75944203]
   [0.22109569 0.20939806]]

  [[0.60436927 0.17524197]
   [0.16430664 0.36968038]
   [0.20844717 0.22258193]]

  [[0.49565525 0.64581418]
   [0.29771893 0.26293604]
   [0.2553924  0.1445173 ]]]]


In [ ]:
d = np.arange(100).reshape(5, 4, 5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [ ]:
a = np.arange(1, 10)
b = a[1:5]
b[0] = 4
print(a)
print(b)
# As you can see changes are applied to both the arrays!
# Even though you might think we are accessing 'b' elements, but both are pointing to the same memory locations 
# Copies of data are not stored in 'b'!

# If you don't want this to happen - 
b = a[1:5].copy()
b[0] = 2
print(a)
print(b)

[1 4 3 4 5 6 7 8 9]
[4 3 4 5]
[1 4 3 4 5 6 7 8 9]
[2 3 4 5]


In [14]:
# Playing with indices
a = np.arange(1, 101)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [15]:
print(a[::3])

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


In [16]:
print(a[::-3])

[100  97  94  91  88  85  82  79  76  73  70  67  64  61  58  55  52  49
  46  43  40  37  34  31  28  25  22  19  16  13  10   7   4   1]


In [19]:
# If you want to find the location of a particular element in the array -> 
idx = np.argwhere(a==4)
print(idx)      # This returns a 2D array, but if you want just the element, use this ->
idx = np.argwhere(a==4)[0][0]
print(idx)

[[3]]
3


Slicing

In [ ]:
a = np.round(10 * np.random.rand(5, 4))
print(a)
print(a[1, 3])
print(a[1,:])
print(a[:,1])
print(a[1:4, 1:4])      # Getting a sub-matrix (rows 1, 2, 3 (not incl 4) and cols 1, 2, 3 (not incl 4))
print(a.T)              # Transpose of matrix

[[ 6.  6.  8.  3.]
 [ 1.  4.  8.  7.]
 [ 7.  0.  5. 10.]
 [ 3.  5.  5.  8.]
 [ 2.  6. 10.  9.]]
7.0
[1. 4. 8. 7.]
[6. 4. 0. 5. 6.]
[[ 4.  8.  7.]
 [ 0.  5. 10.]
 [ 5.  5.  8.]]
[[ 6.  1.  7.  3.  2.]
 [ 6.  4.  0.  5.  6.]
 [ 8.  8.  5.  5. 10.]
 [ 3.  7. 10.  8.  9.]]


In [36]:
import numpy.linalg as la
print(la.inv(np.random.rand(5,5)))


[[-0.96292601  1.77108033 -2.06284571  0.73136234  2.40893043]
 [-0.28626125 -1.04938873  2.0729376  -0.54528533 -0.57887815]
 [-0.57772695  1.62772147  0.27209972 -0.35047529  0.09525559]
 [-1.37362234 -1.00561674  0.81640532  2.17302473 -1.33195   ]
 [ 2.07631295 -0.63584563 -1.05780314 -0.192756    0.40298225]]


In [ ]:
a
a.sort(axis=0)      # Sort array col-wise
a
a.sort(axis=1)      # Sort array row-wise
a

array([[ 0.,  1.,  3.,  5.],
       [ 2.,  4.,  5.,  7.],
       [ 3.,  5.,  8.,  8.],
       [ 6.,  6.,  8.,  9.],
       [ 6.,  7., 10., 10.]])

Fancy Indexing / Marking

In [ ]:
a = np.arange(0, 10)
a[[1,4,6]]          # To access those particular elements that are mentioned
a[[True, False, True, True, False, False, False, True, False, False]]
a[a<6]
a[(a<8) & (a>4)]

# & , and --> arrays, single objects
# | , or --> arrays, single objects
# ~ , not --> arrays, single objects

array([5, 6, 7])

Broadcasting

In [70]:
a = np.array([1, 2, 3, 4])
a = a + 5
b = np.array([1, 2, 3, 4])
b = b + 5
print(a + b)

[12 14 16 18]


In [ ]:
a = np.round(10 * np.random.rand(2, 2))
# print(a)
# a = a + 3
print(a)
print(a + (np.arange(4).reshape(2, 2)))         
# Remember .arange value should be the same as .reshape value (4) = (2, 2) (Basically multiplication)
# Also Broadcasting takes place for same type of matrix (2x2 or 3x3) and not for (2x2 + 3x3) This won't work!

[[3. 3.]
 [7. 3.]]
[[3. 4.]
 [9. 6.]]


In [ ]:
# hstack() --> Horizontally concatenate 2 or more matrices of equal rows! 
a = np.round(np.random.rand(2, 2))
print(a)
b = np.round(np.random.rand(2, 4))
print(b)
c = np.hstack((a, b))       # Give all matrices in tuples!
print(c)

[[0. 0.]
 [1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [96]:

# vstack() --> Horizontally concatenate 2 or more matrices of equal cols! 
a = np.round(np.random.rand(2, 3))
print(a)
b = np.round(np.random.rand(1, 3))
print(b)
c = np.vstack((a, b))
print(c)

[[1. 1. 0.]
 [1. 1. 1.]]
[[1. 1. 0.]]
[[1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]]


In [ ]:
a = np.random.permutation(np.arange(10))
print(a)

a.sort()    # Ascending order
print(a)

print(a[::-1])  # Descending order

[5 4 7 9 6 2 0 8 3 1]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Speed: ufuncs

In [111]:
b = np.round(10 * np.random.rand(10000000))
print(b)
%timeit sum(b)
%timeit np.sum(b)

# You might be thinking that because it is a built-in function, that's why sum(b) is slow. 
# Let's try and make our own function and see then!

def myfunc(b):
    x = 0
    for i in b:
        x += i
    return x

%timeit myfunc(b)
%timeit np.sum(b)

[2. 7. 9. ... 3. 0. 3.]
642 ms ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.05 ms ± 414 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
783 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
6.08 ms ± 517 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
